# Generated by Django 4.2.4 on 2023-08-30 17:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AddAttraction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('city', models.TextField(max_length=100)),
                ('name', models.TextField(max_length=500)),
                ('latitude', models.FloatField(null=True)),
                ('longitude', models.FloatField(null=True)),
                ('photos', models.TextField(max_length=100)),
                ('review_score', models.TextField(max_length=20, null=True)),
                ('description', models.TextField(max_length=1000, null=True)),
                ('website', models.TextField(max_length=100, null=True)),
                ('real_price', models.TextField(max_length=200, null=True)),
                ('hours', models.TextField(max_length=150, null=True)),
                ('tel', models.TextField(max_length=100, null=True)),
                ('address', models.TextField(max_length=100, null=True)),
                ('place_id', models.TextField(max_length=150, null=True)),
                ('tips', models.TextField(max_length=3000, null=True)),
            ],
        ),
    ]
