# Generated by Django 4.2.4 on 2023-08-31 11:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_city_remove_addattraction_place_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='city',
            name='latitude',
        ),
        migrations.RemoveField(
            model_name='city',
            name='longitude',
        ),
    ]
