# Generated by Django 4.2.4 on 2023-09-01 13:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_remove_city_latitude_remove_city_longitude'),
    ]

    operations = [
        migrations.CreateModel(
            name='Night_Life',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(max_length=500)),
                ('latitude', models.FloatField(null=True)),
                ('longitude', models.FloatField(null=True)),
                ('photos', models.TextField(max_length=100)),
                ('review_score', models.TextField(max_length=20, null=True)),
                ('category', models.TextField(max_length=1000, null=True)),
                ('website', models.TextField(max_length=100, null=True)),
                ('price_range', models.IntegerField(null=True)),
                ('hours', models.TextField(max_length=150, null=True)),
                ('tel', models.TextField(max_length=100, null=True)),
                ('address', models.TextField(max_length=100, null=True)),
                ('tips', models.TextField(max_length=3000, null=True)),
                ('city', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='night_life', to='app.city')),
            ],
        ),
    ]
