# Generated by Django 4.2.4 on 2023-09-02 11:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_city_latitude_city_longitude'),
    ]

    operations = [
        migrations.AlterField(
            model_name='night_life',
            name='latitude',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='night_life',
            name='longitude',
            field=models.FloatField(),
        ),
    ]
